openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-refdata-courthearing-judges/0.0.1

info:
  description: Court House API
  version: 0.0.1
  title: api-cp-refdata-courthearing-judges
  contact:
    email: api@hmcts.com
  license:
    name: MIT
    url: 'https://cdn.jsdelivr.net/gh/hmcts/api-cp-refdata-courthearing-courthouses/refs/heads/master/LICENSE'

paths:
  /judges/{judge_id}:
    get:
  
      parameters:
      
        - in: path
          name: judge_id
          required: true
          description: Unique reference number for the court house
          schema:
            type: string
       
      responses:
        '200':
          description:  judge details found
          
          content:
            application/json:
              schema:
                  $ref: "https://cdn.jsdelivr.net/gh/hmcts/api-cp-refdata-courthearing-judges/refs/heads/master/openapi/v0.0.1/judges.schema.json"
              example:
                judiciary:
                  johTitle: "His Honour"
                  johNameSurname: "John Smith"
                  role: "judge"
                  johKnownAs: "His Honour Judge Smith"
    
      
        '400':
          description: bad input parameter
