name: Code analysis

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  pmd-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run PMD analysis using Docker
        run: |
          mkdir -p build/reports/pmd
          run_pmd() {
            docker run --rm -v "$PWD":/src -w /src pmdcode/pmd:latest "$@"
          }
          run_pmd check \
            --dir src/main/java \
            --rulesets \
            category/java/bestpractices.xml, \
            category/java/codestyle.xml, \
            category/java/errorprone.xml, \
            category/java/performance.xml, \
            category/java/security.xml \
            --format xml \
            -r build/reports/pmd/pmd-report.xml

      - name: Convert PMD XML to HTML report
        run: |
          sudo apt-get install -y xsltproc
          wget https://raw.githubusercontent.com/pmd/pmd/master/pmd-core/etc/xslt/cpdhtml.xslt
          xsltproc cpdhtml.xslt pmd-report.xml > pmd-report.html

      - name: Upload PMD HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd/pmd-report.html

      - name: Fail build if violations are found
        run: |
          if grep -q "<violation" pmd-report.xml; then
            echo "PMD violations found"
            cat pmd-report.xml
            exit 1
          else
            echo "No PMD violations"
          fi
