name: Code analysis

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  pmd-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PMD CLI
        run: |
          curl -L -o pmd-dist-7.13.0-bin.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.13.0/pmd-dist-7.13.0-bin.zip
          unzip pmd-dist-7.13.0-bin.zip
          mv pmd-bin-7.13.0 /opt/pmd
          echo "/opt/pmd/bin" >> $GITHUB_PATH

      - name: Run PMD CLI analysis
        run: |
          mkdir -p build/reports/pmd
          
          set +e
          /opt/pmd/bin/pmd check \
            --dir src/main/java \
            --rulesets \
            category/java/bestpractices.xml, \
            category/java/codestyle.xml, \
            category/java/errorprone.xml, \
            category/java/performance.xml, \
            category/java/security.xml \
            --format html \
            -r build/reports/pmd/pmd-report.html
          PMD_EXIT_CODE=$?
          set -e
          
          if [[ "$PMD_EXIT_CODE" -eq 1 ]]; then
            echo "Unexpected internal error during PMD execution"
            exit 1
          elif [[ "$PMD_EXIT_CODE" -eq 2 ]]; then
            echo "CLI usage error"
            exit 1
          fi
          echo "PMD_EXIT_CODE=$PMD_EXIT_CODE" >> $GITHUB_ENV

#      - name: Install xsltproc
#        run: sudo apt-get update && sudo apt-get install -y xsltproc
#
#      - name: Convert PMD XML to HTML report
#        run: |
#          curl -L -o cpdhtml.xslt https://raw.githubusercontent.com/pmd/pmd/refs/heads/main/pmd-core/etc/xslt/cpdhtml.xslt
#          xsltproc pmd-html.xslt build/reports/pmd/pmd-report.xml > build/reports/pmd/pmd-report.html

      - name: Upload PMD HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd/pmd-report.html

      - name: Fail build if violations are found
        run: |
          if [[ "$PMD_EXIT_CODE" -eq 0 ]]; then
            echo "No PMD violations"
          else
            echo "PMD violations found"
            exit 1
          fi
