name: Push Draft OpenAPI Spec to APIHub
description: |
  This workflow pushes a draft version of the OpenAPI spec to APIHub.
  It is triggered by the `workflow_call` event and requires an API key and other inputs.
  The OpenAPI spec is expected to be downloaded as an artifact before this workflow runs.

on:
  workflow_call:
    secrets:
      SWAGGERHUB_API_KEY:
        required: true
    inputs:
      upload_artifact_name:
        required: true
        type: string
      apihub_owner:
        required: true
        type: string
      api_name:
        required: true
        type: string
      api_version:
        required: true
        type: string

jobs:
  Push-API-to-APIHub:
    runs-on: ubuntu-latest
    steps:
      - name: Download versioned OpenAPI spec
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.upload_artifact_name }}
          path: ./

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install SwaggerHub CLI
        run: npm install -g swaggerhub-cli

      - name: Set CLI_API_REF env var
        env:
          SWAGGERHUB_API_KEY: ${{ inputs.is_release }}
          APIHUB_OWNER: ${{ vars.APIHUB_ORGANISATION }}
          API_NAME: ${{ inputs.api_name }}
          API_VERSION: ${{ inputs.api_version }}
        run: |
          echo "CLI_API_REF=${APIHUB_OWNER}/${API_NAME}/${API_VERSION}" >> "$GITHUB_ENV"

      - name: Push API definition into API Hub (UNPUBLISHED)
        # https://github.com/SmartBear/swaggerhub-cli?tab=readme-ov-file#swaggerhub-apicreate
        run: |
          swaggerhub api:create "${CLI_API_REF}" --file openapi-versioned.yml --visibility public

      - name: Check the API definition exists
        # https://github.com/SmartBear/swaggerhub-cli?tab=readme-ov-file#swaggerhub-apiget
        run: |
          set -o pipefail
          if ! swaggerhub api:get "${CLI_API_REF}" 2>&1 | tee error.log; then
            echo "❌ API definition was not found on APIHub"
            echo "--- CLI Error Output ---"
            cat error.log
            exit 1
          fi

      - name: Validate definition
        # https://github.com/SmartBear/swaggerhub-cli?tab=readme-ov-file#swaggerhub-apivalidate
        run: |
          set -o pipefail
          if ! swaggerhub api:validate "${CLI_API_REF}" 2>&1 | tee error.log; then
            echo "❌ OpenAPI definition failed validation"
            echo "--- CLI Error Output ---"
            cat error.log
            exit 1
          fi
